### ISSUE TITLE
Unexpected type mismatch in "load"

### ISSUE THREAD

**Issue by brinux** [xsahil03x/super_pager#17]
**Describe the bug**
In the "load" method of my PagingSource implementation I'm getting a type mismatch error:
type '_$RefreshImpl<dynamic>' is not a subtype of type 'LoadParams<int>' of 'params'

**To Reproduce**
I'm trying to use a bidirectional list, but as I load it I get the following error and can see only the circular spinner:
```stacktrace
I/flutter ( 9335): Data length: 0
E/flutter ( 9335): [ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: type '_$RefreshImpl<dynamic>' is not a subtype of type 'LoadParams<int>' of 'params'
E/flutter ( 9335): #0      MySource.load (package:.../cardList.dart:22:60) --> this is the signature of the "load" method
E/flutter ( 9335): #1      PageFetcher._doInitialLoad.<anonymous closure>.<anonymous closure> (package:super_paging/src/page_fetcher.dart:111:30)
E/flutter ( 9335): #2      new Future.<anonymous closure> (dart:async/future.dart:258:40)
E/flutter ( 9335): #3      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter ( 9335): #4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter ( 9335): #5      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter ( 9335): #6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

I'm pretty sure I'm doing something wrong, but I'm not getting what!

My PagingSource looks like this:

```dart
class MySource extends PagingSource<int, CardData> {
  ...

  @override
  Future<LoadResult<int, CardData>> load(LoadParams<int> params) async {
    var pageToLoad = params.key ?? 0;

    try {
      if (pageToLoad >= 0) {
        ...

        return LoadResult.page(
          items: cards,
          prevKey: pageToLoad - 1,
          nextKey: pageToLoad + 1,
        );
      } else {
        ...

        return LoadResult.page(
          items: cards,
          prevKey: pageToLoad - 1,
          nextKey: pageToLoad + 1,
        );
      }
    } catch (e) {
      return LoadResult.error(e);
    }
}
```

My widget looks like this:

```dart
class MyCardListState extends State<MyCardList> {
  @override
  void initState() {
    super.initState();

    pager = Pager(
      initialKey: 0,
      config: const PagingConfig(pageSize: 20, initialLoadSize: 60),
      pagingSourceFactory: () => MySource(...),
    );
  }

  @override
  void dispose() {
    pager.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    print("Data length: ${_data.length}");

    return BidirectionalPagingListView(
      pager: pager,

      itemBuilder: (BuildContext context, int index) {
        final card = pager.items.elementAt(index);

        return Card(
           ...
          );
      },

      emptyBuilder: (BuildContext context) {
        return const Center(
          child: Text('No characters found'),
        );
      },

      errorBuilder: (BuildContext context, Object? error) {
        return Center(child: Text('$error'));
      },

      loadingBuilder: (BuildContext context) {
        return const Center(
          child: CircularProgressIndicator.adaptive(),
        );
      },
    );
  }
```

Should I manually set the initialState?
Shouldn't I always return prevKey and nextKey?
Is my custom "Card" type a problem?

Thanks in advance!

**Comment by xsahil03x** [comment]
Hey @brinux , this should not occur. Can you share an example repo where I can try to reproduce it? Thanks

**Comment by brinux** [comment]
Hi @xsahil03x, thanks for your help!
I forked your repo and modified it adding a reproduction of my issue. You can find it here: https://github.com/brinux/BiInfiniteScroller
It leverages ObjectBox as an ORM; if I did it right, it should create an in-memory DB and create 100 random entities in it. Then, it tries to create a bi-directional list of them. I couldn't really try it since the error occurs before data loading.
Also, I had to update the Gridle plugin to 8.1, as asked by Flutter.
Please let me know if I can provide help!

**Comment by xsahil03x** [comment]
Hey @brinux , i found the problem. You forgot to define the types while creating the Pager.

```dart
late final Pager<int, Event> pager;
```

This should fix your issue 👍🏼

**Comment by brinux** [comment]
Thanks a lot @xsahil03x! Now it works! ;-)
I'm sorry I missed it!
